#!/usr/bin/env bash

list_dir='/usr/local/etc/'
list_file="${list_dir}/list.tudu"

function create_list_dir {
  mkdir -p "${list_dir}"
}

function print_usage {
  echo "$(basename "$0") [ --add | --delete | --list | --help ]"
}

function add_item {
  echo "${list_item}" >> "${list_file}"
}

function create_list {
  touch "${list_file}"
}

function delete_list_item {
  sed -i '' "${line_num}d" "${list_file}"
}

function read_list {
  line_num=1
  while IFS='' read -r line; do
    echo "${line_num}. ${line}"
    line_num=$((line_num + 1))
  done < "${list_file}"
}

if [[ $# -eq 0 ]]; then
  print_usage
fi

if [ ! -d "${list_dir}" ]; then
  create_list_dir
fi

while [[ $# -gt 0 ]]
do

  key="${1}"

  case "${key}" in
    
    -a|--add)
      shift
      list_item="$*"
      add_item
      exit
    ;;
    
    -d|--delete)
      line_num="${2}"
      delete_list_item
      exit
    ;;
    
    -l|--list)
      read_list
      exit
    ;;
    
    -h|--help)
      print_usage
      exit
    ;;

    *)
      echo "Invalid Argument"
      print_usage
      exit
    ;;

  esac

done
